apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certmanager
  namespace: certmanager
spec:
  releaseName: certmanager
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 'v1.6.1'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: true